# Specifying the ApiVersion
apiVersion: eksctl.io/v1alpha5

# Specifying the kind of the resource
kind: ClusterConfig

# Specifying the metadata of the cluster to launch!
metadata:
 # Specifying the name of the cluster!
  name: TWClsuter

  # Specifying the region in which we have to launch the cluster.
  region: us-east-1

nodeGroups:
  - name: ng-1
    desiredCapacity: 3
    instanceType: t2.micro
    ssh:
      publicKeyName: GeneralKey