apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twns-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
      tier: best-database
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cassandra
        tier: best-database
    spec:
      containers:
      - image: continuumio/anaconda3
        name: anaconda
        volumeMounts:
        - name: cassandra-persistent-storage
          mountPath: /var/lib/cassandra
      volumes:
      - name: cassandra-persistent-storage
        persistentVolumeClaim:
          claimName: twns-pvc
